export enum RotasApi {
    agendamentos = 'agendamentos',
    agendas = 'agendas',
    bloqueioAgendas = 'bloqueioAgendas',
    bloqueioProfissionais = 'bloqueioProfissionais',
    categoriaServicos = 'categoriaServicos',
    clientes = 'clientes',
    clientesAnamnese = 'clientesAnamnese',
    clientesEvolucao = 'clientesEvolucao',
    comandas = 'comandas',
    comandasAuditoria = 'comandasAuditoria',
    comissoes = 'comissoes',
    comissoesVales = 'comissoesVales',
    comissoesPagamentos = 'comissoesPagamentos',  
    configuracaoHorarios = 'configuracaoHorarios',
    contaCorrenteCliente = 'contaCorrenteCliente',
    descontoTaxaCartao = 'descontoTaxaCartao',
    despesas = 'despesas',
    empresas = 'empresas',
    leads = 'leads',
    lembretesCredito = 'lembretesCredito',
    lembretesLog = 'lembretesLog',
    lembretesSaldo = 'lembretesSaldo',
    maquinaCartao = 'maquinaCartao',
    produtos = 'produtos',
    produtosEstoque = 'produtosEstoque',
    profissionais = 'profissionais',
    sangrias = 'sangrias',
    servicos = 'servicos',
    suprimentos = 'suprimentos',
    templateServicos = "templateServicos",
    usuarios = 'usuarios',
    videosYoutube = 'videos-youtube',
  }
  